from fastapi import APIRouter, Query
from typing import Optional
from app.services.ml_forecast_service import forecaster

router = APIRouter(prefix="/forecast", tags=["ML Blood Demand Forecast"])

@router.get("/7-days")
def get_7_day_forecast(
    district: Optional[str] = Query(None, description="Optional Tamil Nadu district name")
):
    """
    Returns actual machine-learning forecast generated by Scikit-Learn RandomForestRegressor.
    Predicts 7-day volume per blood group, urgency flags, and shortage risks.
    """
    return forecaster.forecast_7_days(district=district)
